services:
  mysql:
    container_name: mysql_db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "db_pruebas"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"
    ports:
      - 3306:3306
    volumes:
      - ./schemas:/var/lib/mysql

volumes:
  schemas: {}

